[package]
name = "mtt"
version = "1.0.0"
edition = "2021"

[profile.release]
opt-level = 3

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
image = "0.24.6"
rodio = "0.17.1"
indicatif = "0.17.5"
termion = "2.0.1"
rayon = "1.7.0"
